# Generated by Django 4.2.23 on 2025-09-12 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Слаг')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')),
                ('kind', models.CharField(choices=[('fruit', 'Фрукты'), ('vegetable', 'Овощи'), ('grain', 'Зерновые'), ('dairy', 'Молочные'), ('meat', 'Мясо'), ('fish', 'Рыба и морепродукты'), ('nuts', 'Орехи'), ('legumes', 'Бобовые'), ('spice', 'Специи'), ('other', 'Другое')], default='other', max_length=32, verbose_name='Вид')),
                ('kcal', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Калории (ккал/100г)')),
                ('proteins', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Белки (г/100г)')),
                ('fats', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Жиры (г/100г)')),
                ('carbs', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Углеводы (г/100г)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='products.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
