# Generated by Django 4.2.23 on 2025-09-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(blank=True, max_length=120, verbose_name='Сорт / вид'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'kind'), name='uniq_product_name_kind'),
        ),
    ]
