# Generated by Django 4.2.23 on 2025-09-12 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Базовое название')),
                ('kind', models.CharField(blank=True, max_length=120, verbose_name='Сорт / вид')),
                ('group', models.CharField(blank=True, max_length=32, verbose_name='Группа')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='proposals/', verbose_name='Фото (опц.)')),
                ('kcal', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Ккал/100г')),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Белки/100г')),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Жиры/100г')),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Углеводы/100г')),
                ('categories_text', models.CharField(blank=True, help_text='Напр.: Фрукты, Осенние, Розовые', max_length=200, verbose_name='Категории (через запятую)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий автора')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=16, verbose_name='Статус')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Заявка на продукт',
                'verbose_name_plural': 'Заявки на продукты',
                'ordering': ['-created_at'],
            },
        ),
    ]
