# Generated by Django 5.2.6 on 2025-09-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productproposal',
            name='group',
        ),
        migrations.AlterField(
            model_name='productproposal',
            name='categories_text',
            field=models.CharField(blank=True, help_text='Напр.: Фрукты, Овощи, Напитки и т.д.', max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='productproposal',
            name='kind',
            field=models.CharField(blank=True, max_length=120, verbose_name='Вид'),
        ),
    ]
